baseURL = "https://ilar.in/"
languageCode = "en-us"
title = "ilar.in"
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "ilar.in"
  description = "Ilari's blog"
  author = "Ilari"
  defaultTheme = "auto"
  disableSpecial1stPost = true
  ShowReadingTime = true
  ShowWordCount = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  comments = false
  hidemeta = false
  hideSummaryInList = false

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
